export const LABEL_GLYPH_MAP = new Map([
  [
    ' ',
    {
      x: 2,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: 0,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 0,
      boxDescent: 0,
      boxWidth: 5,
    },
  ],
  [
    '!',
    {
      x: 12,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 3,
    },
  ],
  [
    '"',
    {
      x: 22,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: -7,
      boxWidth: 4,
    },
  ],
  [
    '#',
    {
      x: 33,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '$',
    {
      x: 47,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 7,
    },
  ],
  [
    '%',
    {
      x: 61,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    '&',
    {
      x: 77,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    "'",
    {
      x: 93,
      y: 2,
      width: 4,
      height: 13,
      advance: 3,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: -7,
      boxWidth: 1,
    },
  ],
  [
    '(',
    {
      x: 101,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    ')',
    {
      x: 112,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    '*',
    {
      x: 123,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '+',
    {
      x: 137,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 9,
      boxDescent: -1,
      boxWidth: 7,
    },
  ],
  [
    ',',
    {
      x: 151,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 3,
      boxDescent: 2,
      boxWidth: 3,
    },
  ],
  [
    '-',
    {
      x: 161,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 6,
      boxDescent: -4,
      boxWidth: 6,
    },
  ],
  [
    '.',
    {
      x: 174,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 3,
      boxDescent: 0,
      boxWidth: 3,
    },
  ],
  [
    '/',
    {
      x: 184,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 4,
    },
  ],
  [
    '0',
    {
      x: 195,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '1',
    {
      x: 209,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 4,
    },
  ],
  [
    '2',
    {
      x: 220,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '3',
    {
      x: 234,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '4',
    {
      x: 248,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '5',
    {
      x: 262,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '6',
    {
      x: 276,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '7',
    {
      x: 290,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '8',
    {
      x: 304,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '9',
    {
      x: 318,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    ':',
    {
      x: 332,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 3,
    },
  ],
  [
    ';',
    {
      x: 342,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 2,
      boxWidth: 3,
    },
  ],
  [
    '<',
    {
      x: 352,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    '=',
    {
      x: 365,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 6,
      boxDescent: -1,
      boxWidth: 6,
    },
  ],
  [
    '>',
    {
      x: 378,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    '?',
    {
      x: 391,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '@',
    {
      x: 405,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 9,
      boxDescent: 2,
      boxWidth: 9,
    },
  ],
  [
    'A',
    {
      x: 421,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'B',
    {
      x: 435,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'C',
    {
      x: 449,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'D',
    {
      x: 463,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'E',
    {
      x: 477,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'F',
    {
      x: 491,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'G',
    {
      x: 505,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'H',
    {
      x: 519,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'I',
    {
      x: 533,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 3,
    },
  ],
  [
    'J',
    {
      x: 543,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    'K',
    {
      x: 556,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'L',
    {
      x: 572,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    'M',
    {
      x: 585,
      y: 2,
      width: 13,
      height: 13,
      advance: 12,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 10,
    },
  ],
  [
    'N',
    {
      x: 602,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'O',
    {
      x: 618,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'P',
    {
      x: 634,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'Q',
    {
      x: 648,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 9,
    },
  ],
  [
    'R',
    {
      x: 664,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'S',
    {
      x: 678,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    'T',
    {
      x: 691,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'U',
    {
      x: 707,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'V',
    {
      x: 721,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'W',
    {
      x: 737,
      y: 2,
      width: 13,
      height: 13,
      advance: 12,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 10,
    },
  ],
  [
    'X',
    {
      x: 754,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'Y',
    {
      x: 770,
      y: 2,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    'Z',
    {
      x: 786,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '[',
    {
      x: 800,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    '\\',
    {
      x: 811,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 4,
    },
  ],
  [
    ']',
    {
      x: 822,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    '^',
    {
      x: 833,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: -6,
      boxWidth: 4,
    },
  ],
  [
    '_',
    {
      x: 844,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 2,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    '`',
    {
      x: 858,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: -7,
      boxWidth: 3,
    },
  ],
  [
    'a',
    {
      x: 868,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'b',
    {
      x: 882,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'c',
    {
      x: 896,
      y: 2,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    'd',
    {
      x: 909,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'e',
    {
      x: 923,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'f',
    {
      x: 937,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 4,
    },
  ],
  [
    'g',
    {
      x: 948,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 2,
      boxWidth: 7,
    },
  ],
  [
    'h',
    {
      x: 962,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'i',
    {
      x: 976,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 3,
    },
  ],
  [
    'j',
    {
      x: 986,
      y: 2,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    'k',
    {
      x: 997,
      y: 2,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'l',
    {
      x: 1011,
      y: 2,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 3,
    },
  ],
  [
    'm',
    {
      x: 2,
      y: 19,
      width: 15,
      height: 13,
      advance: 14,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 12,
    },
  ],
  [
    'n',
    {
      x: 21,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'o',
    {
      x: 35,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'p',
    {
      x: 49,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 2,
      boxWidth: 7,
    },
  ],
  [
    'q',
    {
      x: 63,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 2,
      boxWidth: 7,
    },
  ],
  [
    'r',
    {
      x: 77,
      y: 19,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    's',
    {
      x: 90,
      y: 19,
      width: 9,
      height: 13,
      advance: 8,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 6,
    },
  ],
  [
    't',
    {
      x: 103,
      y: 19,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 4,
    },
  ],
  [
    'u',
    {
      x: 114,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'v',
    {
      x: 128,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'w',
    {
      x: 142,
      y: 19,
      width: 13,
      height: 13,
      advance: 12,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 10,
    },
  ],
  [
    'x',
    {
      x: 159,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    'y',
    {
      x: 173,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 2,
      boxWidth: 7,
    },
  ],
  [
    'z',
    {
      x: 187,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 8,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '{',
    {
      x: 201,
      y: 19,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    '|',
    {
      x: 212,
      y: 19,
      width: 6,
      height: 13,
      advance: 5,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 3,
    },
  ],
  [
    '}',
    {
      x: 222,
      y: 19,
      width: 7,
      height: 13,
      advance: 6,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 2,
      boxWidth: 4,
    },
  ],
  [
    '~',
    {
      x: 233,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: -7,
      boxWidth: 7,
    },
  ],
  [
    '€',
    {
      x: 247,
      y: 19,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 9,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
  [
    '£',
    {
      x: 263,
      y: 19,
      width: 10,
      height: 13,
      advance: 9,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 7,
    },
  ],
  [
    '¥',
    {
      x: 277,
      y: 19,
      width: 12,
      height: 13,
      advance: 11,
      bearingX: -1,
      bearingY: 11,
      lineHeight: 13,
      boxAscent: 11,
      boxDescent: 0,
      boxWidth: 9,
    },
  ],
])
