export enum CurseBotState {
  STOPPED,
  RESET_STORE,
  AWAITING_PLAYERS,
  PREPARING_FOR_NEXT_ROUND,
  WAITING_FOR_ALL_PLAYERS_TO_BE_TELEPORTED_TO_MAP,
  COUNTING_DOWN_TO_REMOVE_NO_SPEED,
  PLAYING,
  CELEBRATING_VICTORY,
}
