export enum CopyBotCommandName {
  HELP = 'help',
  PING = 'ping',
  EDIT = 'edit',
  FLIP = 'flip',
  PASTE = 'paste',
  SMART_PASTE = 'smartpaste',
  UNDO = 'undo',
  REDO = 'redo',
  MOVE = 'move',
  MASK = 'mask',
  SKIP_AIR = 'skipair',
  IMPORT = 'import',
  SNAKE = 'snake',
  PLACE_ALL = 'placeall',
  PLACE_EELVL_EXPORT = 'placeeelvlexport',
  PRINT_BLOCKS = 'printblocks',
}
